name: CI with Gradle
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev", "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.DB_YML }}" | base64 --decode > src/main/resources/application.yml
      
      - name: Build and Test with Gradle
        run: ./gradlew test -Dspring.profiles.active=test
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SPRING_AI_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
          
  dependency-submission:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
